### ISSUE TITLE
saving outfit

### ISSUE THREAD

**Issue by eksynn** [XeTrinityz/ThatSkyApp#2]
when saving an outfit, we get stuck on the "save outfit" name screen.. i can't figure out a way past that besides closing the game. last version, saving the outfit did nothing when changing back to the outfit you saved.. but i can't test that in this latest version cuz i can't save lol

edit: i tried ESC-ing and TAB-ng out of the dialogue window, didn't work. alt-tab, nothing. holding ALT to move the cursor, nothing.

edit 2: this only happens if you're NOT paused, so save the outfit with the Esc menu opened.

**Comment by XeTrinityz** [comment]
This will be resolved in the next version.
